[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Gestão de Salas"
authors = [{name = "Matheus Bucater", email = "matheusbucater@gmail.com"}]
dynamic = ["version", "description"]
